# Generated by Django 5.2.5 on 2025-10-12 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_bookings_num_people_bookings_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings_Table',
        ),
    ]
