# Generated by Django 5.2.5 on 2025-10-15 08:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_delete_bookings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
