# Generated by Django 5.2.5 on 2025-10-12 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_alter_bookings_staff_alter_table_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='num_people',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='bookings',
            name='table',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Book.table'),
            preserve_default=False,
        ),
    ]
